openapi: 3.0.0
info:
  version: 0.1.0
  title: Liwanag API
  description: API for Liwanag, a Tagalog language learning application.

paths:
  /users:
    $ref: 'paths/Users.yaml'
  /words:
    $ref: 'paths/Words.yaml'
  /words/{word_id}:
    $ref: 'paths/Word.yaml'
  /sentences:
    $ref: 'paths/Sentences.yaml'
  /sentences/{sentence_id}:
    $ref: 'paths/Sentence.yaml'

components:
  schemas:
    $ref: 'schemas/index.yaml'